<?php

function pr($val = ''){
    echo "<pre>";
    print_r($val);
    echo "</pre>";
}
function prd($val = ''){
    pr($val);
    die();
}

function careconscious_form_user_register_alter(&$form, &$form_state){
  $form['top_markup'] = array('#type' => 'markup', '#value' => '<div id="registration-top-markup">Join today to become a valued member of our community. Get the support and answers you need to be effective, reduce stress, get organized, save time and make effective decisions. Prepared Family Caregivers can even avoid burn out and depression and reduce doctor visits!
<b>Take control, start today and get your customized Family Caregiver\'s Plan.</b></div>', '#weight' => -20);
  $form['name']['#title'] = 'Create a username';
  $form['submit']['#value'] = 'Create Account';
}

function careconscious_cart_item($op, &$item) {
  // Restrict all quantities to 1.
  if ($op == 'load' && $item->qty > 1) {
    $item->qty = 1;
  }
}

function careconscious_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0]['info'] = t('Remarketing Code');
      return $blocks;
    case 'view':
      $block[0]['content'] = '<!-- Google Code for Remarketing, non-conversions Remarketing List -->
<script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 942504911;
var google_conversion_language = "en";
var google_conversion_format = "3";
var google_conversion_color = "ffffff";
var google_conversion_label = "M8aFCNGW8gMQz_e1wQM";
var google_conversion_value = 0;
/* ]]> */
</script>
<script type="text/javascript" src="http://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="http://www.googleadservices.com/pagead/conversion/942504911/?value=0&amp;label=M8aFCNGW8gMQz_e1wQM&amp;guid=ON&amp;script=0"/>
</div>
</noscript>
';
       return $block[$delta];
  }
}